"""
从 Chrome cookie 数据库中提取指定域名的 cookies，导出为 Netscape 格式。
新版 Chrome 使用 AES-GCM 加密 cookie，需要先解密。
"""

import base64
import json
import os
import sqlite3
import shutil
import struct
import tempfile
from pathlib import Path

try:
    import win32crypt
except ImportError:
    win32crypt = None

from cryptography.hazmat.primitives.ciphers.aead import AESGCM


def get_chrome_paths():
    """获取 Chrome 用户数据路径。"""
    local_appdata = os.environ.get("LOCALAPPDATA", "")
    user_data = Path(local_appdata) / "Google" / "Chrome" / "User Data"
    return {
        "local_state": user_data / "Local State",
        "cookies": user_data / "Default" / "Network" / "Cookies",
    }


def get_encryption_key(local_state_path: Path) -> bytes:
    """从 Local State 中提取并解密 AES 密钥。"""
    if not local_state_path.exists():
        raise FileNotFoundError(f"Local State not found: {local_state_path}")

    state = json.loads(local_state_path.read_text(encoding="utf-8"))
    encrypted_key_b64 = state.get("os_crypt", {}).get("encrypted_key", "")
    if not encrypted_key_b64:
        raise ValueError("No encrypted_key found in Local State")

    encrypted_key = base64.b64decode(encrypted_key_b64)
    # 去掉 "DPAPI" 前缀
    if encrypted_key[:5] != b"DPAPI":
        raise ValueError("Unexpected key format")
    encrypted_key = encrypted_key[5:]

    if win32crypt is None:
        raise RuntimeError("win32crypt not available, cannot decrypt key")

    key = win32crypt.CryptUnprotectData(encrypted_key, None, None, None, 0)[1]
    return key


def decrypt_cookie_value(encrypted_value: bytes, key: bytes) -> str:
    """解密 Chrome AES-GCM 加密的 cookie 值。"""
    if not encrypted_value:
        return ""

    # 新版 Chrome 格式: v10/v11 + nonce(12B) + ciphertext + tag(16B)
    if encrypted_value[:3] in (b"v10", b"v11"):
        nonce = encrypted_value[3:15]
        ciphertext = encrypted_value[15:]
        aesgcm = AESGCM(key)
        try:
            return aesgcm.decrypt(nonce, ciphertext, None).decode("utf-8")
        except Exception:
            return "(decrypt_error)"

    # 旧版 Chrome: 使用 DPAPI 直接解密
    if win32crypt:
        try:
            return win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode("utf-8")
        except Exception:
            return "(decrypt_error)"

    return "(no_decrypt)"


def extract_cookies(domain_filter: str = "") -> list[dict]:
    """提取 Chrome cookies，可选按域名过滤。"""
    paths = get_chrome_paths()
    key = get_encryption_key(paths["local_state"])

    # 复制数据库（Chrome 可能锁定文件）
    tmp_db = Path(tempfile.mkdtemp()) / "Cookies"
    shutil.copy2(paths["cookies"], tmp_db)

    conn = sqlite3.connect(tmp_db)
    conn.text_factory = bytes  # 避免编码问题

    if domain_filter:
        cur = conn.execute(
            "SELECT host_key, name, path, is_secure, expires_utc, encrypted_value, is_httponly, has_expires "
            "FROM cookies WHERE host_key LIKE ?",
            (f"%{domain_filter}%",),
        )
    else:
        cur = conn.execute(
            "SELECT host_key, name, path, is_secure, expires_utc, encrypted_value, is_httponly, has_expires "
            "FROM cookies"
        )

    cookies = []
    for row in cur.fetchall():
        host_key = row[0].decode("utf-8") if isinstance(row[0], bytes) else row[0]
        name = row[1].decode("utf-8") if isinstance(row[1], bytes) else row[1]
        path = row[2].decode("utf-8") if isinstance(row[2], bytes) else row[2]
        secure = bool(row[3])
        expires_utc = row[4]
        encrypted_value = row[5]
        httponly = bool(row[6])
        has_expires = bool(row[7])

        value = decrypt_cookie_value(encrypted_value, key)

        cookies.append({
            "domain": host_key,
            "name": name,
            "value": value,
            "path": path,
            "secure": secure,
            "httponly": httponly,
            "expires": expires_utc if has_expires else 0,
        })

    conn.close()
    tmp_db.unlink(missing_ok=True)
    return cookies


def save_netscape(cookies: list[dict], filepath: Path):
    """保存为 Netscape 格式 cookie 文件（yt-dlp 可用）。"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by chrome_cookie_extract.py",
    ]
    for c in cookies:
        domain = c["domain"]
        if not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c["secure"] else "FALSE"
        expires = str(int(c["expires"] / 1_000_000) if c["expires"] else 0)
        lines.append(
            f"{domain}\t{flag}\t{c['path']}\t{secure}\t{expires}\t{c['name']}\t{c['value']}"
        )
    filepath.write_text("\n".join(lines), encoding="utf-8")
    print(f"[完成] 已导出 {len(cookies)} 个 cookies -> {filepath}")


if __name__ == "__main__":
    import sys

    domain = sys.argv[1] if len(sys.argv) > 1 else "douyin.com"
    output = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("douyin_cookies.txt")

    print(f"[信息] 从 Chrome 提取 {domain} 的 cookies...")
    try:
        cookies = extract_cookies(domain)
        save_netscape(cookies, output)
    except Exception as e:
        print(f"[错误] {e}")
        sys.exit(1)
